# fly.toml app configuration file generated for website-twilight-waterfall-8627 on 2025-07-29T16:16:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'website-twilight-waterfall-8627'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
